name: Android CI

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]  

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Check Contents of Directory
      run: cd patients && pwd
    
    - name: Grant execute permission to gradlew
      run: cd patients && chmod +x gradlew

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Set up Android SDK Platform Tools
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30

    - name: Build with Gradle
      run: cd patients && ./gradlew build

    - name: Install and Run on Emulator
      run: |
        cd patients
        adb install patients/build/outputs/apk/debug/your_app_name.apk
        adb shell am start -n com.example.yourapp/.MainActivity

    - name: Run Monkey Test
      run: cd patients && adb shell monkey -p com.patients.main -v 1000  

